version: "3.7"
services:
  nginx:
    image: nginx:1.15-alpine
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
    depends_on:
      - app
    volumes:
      - /etc/nginx/ssl:/etc/nginx/ssl
      - static_volume:/api/static
      - /nrs/kainmueller/PatchPerPixMatch:/nrs/kainmueller/PatchPerPixMatch
    networks:
      - ppp-net
  app:
    #image: registry.int.janelia.org/janeliascicomp/pppm-website
    build: ./api
    restart: unless-stopped
    volumes:
        - static_volume:/api/static
        - /nrs/kainmueller/PatchPerPixMatch:/nrs/kainmueller/PatchPerPixMatch
    environment:
      - TZ=America/New_York
      - PYTHONUNBUFFERED=1
    networks:
        - ppp-net

networks:
  ppp-net:
      driver: bridge

volumes:
  static_volume:
