version: "3.7"
services:
  nginx:
    image: nginx:1.15-alpine
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
    depends_on:
      - app
    volumes:
      - /etc/nginx/ssl:/etc/nginx/ssl
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/api/static
    networks:
      - ppp-net
  app:
    build: ./api
    restart: unless-stopped
    volumes:
        - ./api:/api
        - static_volume:/api/static
    environment:
      - TZ=America/New_York
      - PYTHONUNBUFFERED=1
    networks:
        - ppp-net

networks:
  ppp-net:
      driver: bridge

volumes:
  static_volume:
